---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - topolvm.io
  resources:
  - volumegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - topolvm.io
  resources:
  - volumegroups/finalizers
  verbs:
  - update
- apiGroups:
  - topolvm.io
  resources:
  - volumegroups/status
  verbs:
  - get
  - patch
  - update
