# permissions for end users to edit volumegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: topovgm
    app.kubernetes.io/managed-by: kustomize
  name: volumegroup-editor-role
rules:
- apiGroups:
  - topolvm.io
  resources:
  - volumegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - topolvm.io
  resources:
  - volumegroups/status
  verbs:
  - get
