name: Test

on:
  pull_request:
    paths-ignore:
      - "**/*.md"
  push:
    paths-ignore:
      - "**/*.md"
    branches:
      - "main"
env:
  IMAGE_NAME: topovgm
  IMAGE_ARTIFACT: topovgm-ci-container-image
jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          outputs: type=docker,dest=/tmp/${{ env.IMAGE_ARTIFACT }}.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IMAGE_ARTIFACT }}
          path: /tmp/${{ env.IMAGE_ARTIFACT }}.tar
    outputs:
      meta: ${{ steps.meta.outputs.json }}

  unit-tests:
    env:
      GOTOOLCHAIN: local
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.22.5' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version
      - name: Run tests
        run: sudo make test

  e2e-minikube:
    needs: image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
      - name: cache go dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-${{ hashFiles('go.sum', 'Makefile') }}
          restore-keys: |
            go-

      - name: Get Image from Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.IMAGE_ARTIFACT }}
          path: /tmp

      - name: install dependencies of minikube
        env:
          CNI_PLUGINS_VERSION: v1.5.1
          CRI_DOCKERD_VERSION: v0.3.14
          CRICTL_VERSION: v1.30.1
        run: |
          curl -L -o cni-plugins.tgz https://github.com/containernetworking/plugins/releases/download/${{ env.CNI_PLUGINS_VERSION }}/cni-plugins-linux-amd64-${{ env.CNI_PLUGINS_VERSION }}.tgz
          sudo mkdir -p /opt/cni/bin
          sudo tar -C /opt/cni/bin -xzf cni-plugins.tgz

          # Install cri-docker
          git clone -n https://github.com/Mirantis/cri-dockerd
          cd cri-dockerd
          git checkout ${{ env.CRI_DOCKERD_VERSION }}
          mkdir bin
          go get && go build -o bin/cri-dockerd
          mkdir -p /usr/local/bin
          sudo install -o root -g root -m 0755 bin/cri-dockerd /usr/local/bin/cri-dockerd
          sudo cp -a packaging/systemd/* /etc/systemd/system
          sudo sed -i -e 's,/usr/bin/cri-dockerd,/usr/local/bin/cri-dockerd,' /etc/systemd/system/cri-docker.service

          # This is a workaround for the following issue.
          # https://github.com/kubernetes/minikube/issues/15265
          sudo ln -s /usr/local/bin/cri-dockerd /usr/bin/cri-dockerd

          sudo systemctl daemon-reload
          sudo systemctl enable cri-docker.service
          sudo systemctl enable --now cri-docker.socket
          curl -L https://github.com/kubernetes-sigs/cri-tools/releases/download/${{ env.CRICTL_VERSION }}/crictl-${{ env.CRICTL_VERSION }}-linux-amd64.tar.gz --output crictl-${{ env.CRICTL_VERSION }}-linux-amd64.tar.gz
          sudo tar zxvf crictl-${{ env.CRICTL_VERSION }}-linux-amd64.tar.gz -C /usr/local/bin
      - run: make -C test/e2e setup
      - run: make -C test/e2e launch

      - name: determine node
        id: nodename
        run: |
          echo "node=$(kubectl get node -oyaml | yq -r .items[0].metadata.name)" >> $GITHUB_OUTPUT
      - name: set node name on sample
        uses: mikefarah/yq@master
        with:
          cmd: yq -i -e ".spec.nodeName = \"${{ steps.nodename.outputs.node }}\"" config/samples/topolvm_v1alpha1_volumegroup.yaml
      - name: Load image into Docker
        run: |
          docker load --input /tmp/${{ env.IMAGE_ARTIFACT }}.tar
          docker image ls -a
      - run: make test-e2e
        env:
          IMAGE_NAME: ${{ fromJSON(needs.image.outputs.meta).tags[0] }}


  e2e-k3d:
    env:
      K3D_NODE_IMAGE: localhost/k3d-node-image
    needs: image
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Install k3d
        run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
      - name: Create k3d cluster with Flannel
        run: |
          k3d cluster create \
            --image ghcr.io/jakobmoellerdev/k3s:alpine-latest \
            --k3s-arg "--disable=traefik@server:*" \
            --k3s-arg "--disable=servicelb@server:*" \
            --k3s-arg "--node-name=test-node"@server:0 \
            --volume /dev:/dev
      - name: Access loop device from nodes
        run: |
          for node in $(k3d node list -o json | jq -r '.[].name'); do
            docker exec $node ls /dev/loop*
            echo "Setting up loop devices on $node"
            docker exec $node sh -c 'export DEVICE=0 && dd if=/dev/zero of=/tmp/lblock$DEVICE bs=4K count=262144 && losetup -f /tmp/lblock$DEVICE && echo "Using loop device $(losetup -j /tmp/lblock$DEVICE)"'
          done
      - name: Get Image from Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.IMAGE_ARTIFACT }}
          path: /tmp
      - name: Load image
        run: |
          k3d image import /tmp/${{ env.IMAGE_ARTIFACT }}.tar

      - run: make test-e2e
        env:
          IMAGE_NAME: ${{ fromJSON(needs.image.outputs.meta).tags[0] }}